import { test, expect } from '@playwright/test'

const FULL_AUDIT = {
  url: 'https://books.toscrape.com',
  total_bytes: 51200,
  script_ratio: 25.4,
  extractable_text_pct: 12.8,
  raw_html: '<html><body><h1>Books to Scrape</h1><p>Price: $50.00</p></body></html>',
  markdown: '# Books to Scrape\n\n- [A Light in the Attic](https://books.toscrape.com/a-light) — Price: $51.77',
  generated_llms_txt:
    '# Books to Scrape\n\n> Machine-readable storefront summary generated by AGORA.\n> Source: https://books.toscrape.com\n\n## Products (57)\n\n- [A Light in the Attic](https://books.toscrape.com/a-light) — Price: 51.77\n- …preview truncated: 47+ more product lines in the full file, delivered with the AGORA install package.',
  llms_txt_truncated: true,
  catalog: {
    source: 'products_json',
    total_count: 57,
    visible_to_agent: 3,
    coverage_pct: 5.3,
    sample: [{ name: 'A Light in the Attic', url: 'https://books.toscrape.com/a-light', price: 51.77 }],
  },
  checklist: {
    llms_txt: { pass_status: true, evidence: 'Found /llms.txt with 1 priced product line' },
    product_content: { pass_status: true, evidence: 'Found product indicator tokens: price, product, stock' },
    schema_org: { pass_status: true, evidence: 'Found schema.org Product markup' },
    robots_txt: { pass_status: true, evidence: 'robots.txt does not block known agent user-agents on this path' },
  },
}

test.describe('AGORA — AI Agent Traffic & Storefront Auditor', () => {

  test('initial load: hero, branding, navigation tabs, and audit input are visible', async ({ page }) => {
    await page.goto('/')
    await expect(page.getByText('AGORA', { exact: true })).toBeVisible()
    await expect(page.getByRole('heading', { name: "Your next customer isn't human." })).toBeVisible()
    await expect(page.locator('input[placeholder="https://your-store.com"]')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Run Agent Audit' })).toBeVisible()
  })

  test('landing page renders pipeline steps and agent signatures', async ({ page }) => {
    await page.goto('/')
    await expect(page.getByRole('heading', { name: 'See. Be readable. Then sell.' })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Detect' })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Audit' })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Serve' })).toBeVisible()
    await expect(page.getByText('ChatGPT-User')).toBeVisible()
    await expect(page.getByText('ClaudeBot')).toBeVisible()
  })

  test('tab navigation works smoothly across all views', async ({ page }) => {
    await page.goto('/')

    // Navigate to Live Feed
    await page.getByRole('button', { name: 'Live Request Feed' }).click()
    await expect(page.getByRole('heading', { name: 'Live Request Feed' })).toBeVisible()

    // Navigate to Auditor
    await page.getByRole('button', { name: 'AI Storefront Auditor' }).click()
    await expect(page.getByRole('heading', { name: 'AI Storefront Auditor' })).toBeVisible()

    // Navigate to Agent Intelligence
    await page.getByRole('button', { name: 'Agent Intelligence' }).click()
    await expect(page.getByRole('heading', { name: 'Agent Intelligence' })).toBeVisible()

    // Navigate to Leads / Admin
    await page.getByRole('button', { name: 'Leads' }).click()
    await expect(page.getByRole('heading', { name: 'Leads' })).toBeVisible()

    // Return to Overview
    await page.getByRole('button', { name: 'Overview' }).click()
    await expect(page.getByRole('heading', { name: "Your next customer isn't human." })).toBeVisible()
  })

  test('audit from hero input triggers crawl, switches to Auditor tab, and renders full audit result', async ({ page }) => {
    await page.route('**/report/analyze', async route => {
      await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(FULL_AUDIT) })
    })

    await page.goto('/')
    await page.getByPlaceholder('https://your-store.com').fill('books.toscrape.com')
    await page.getByRole('button', { name: 'Run Agent Audit' }).click()

    // Verifies transition to Auditor tab
    await expect(page.getByRole('heading', { name: 'AI Storefront Auditor' })).toBeVisible()

    // 1) Catalog Reality Card
    await expect(page.getByText('Catalog Reality vs Agent View')).toBeVisible()
    await expect(page.getByText('57', { exact: true })).toBeVisible()
    await expect(page.getByText('5.3%')).toBeVisible()

    // 2) Computed Crawl Metrics
    await expect(page.getByText('Computed Crawl Metrics')).toBeVisible()
    await expect(page.getByText('25.4%')).toBeVisible()
    await expect(page.getByText('12.8%')).toBeVisible()

    // 3) AI Readiness Checklist
    await expect(page.getByText('AI Readiness Checklist')).toBeVisible()
    await expect(page.getByText('/llms.txt exists and serves your catalog')).toBeVisible()
    await expect(page.getByText('Product pricing & metadata parsed')).toBeVisible()

    // 4) Generated llms.txt view
    await expect(page.getByText('# Books to Scrape')).toBeVisible()
    await expect(page.getByText('Preview', { exact: true })).toBeVisible()

    // 5) Toggle to Agent's-eye view (markdown)
    await page.getByRole('button', { name: "Agent's-eye view" }).click()
    await expect(page.getByText('A Light in the Attic')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Copy' })).toBeVisible()
  })

  test('auditor tab quick target buttons trigger audit execution', async ({ page }) => {
    await page.route('**/report/analyze', async route => {
      await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(FULL_AUDIT) })
    })

    await page.goto('/')
    await page.getByRole('button', { name: 'AI Storefront Auditor' }).click()
    await expect(page.getByRole('button', { name: 'Books to Scrape (Demo Store)' })).toBeVisible()

    await page.getByRole('button', { name: 'Books to Scrape (Demo Store)' }).click()
    await expect(page.getByText('Computed Crawl Metrics')).toBeVisible()
    await expect(page.getByText('Catalog Reality vs Agent View')).toBeVisible()
  })

  test('error message displays when crawl request fails', async ({ page }) => {
    await page.route('**/report/analyze', async route => {
      await route.fulfill({
        status: 400,
        contentType: 'application/json',
        body: JSON.stringify({ detail: 'Refused to fetch URL: Host localhost resolves to non-public address 127.0.0.1' }),
      })
    })

    await page.goto('/')
    await page.getByPlaceholder('https://your-store.com').fill('http://127.0.0.1:8000')
    await page.getByRole('button', { name: 'Run Agent Audit' }).click()

    await expect(page.getByText('Refused to fetch URL: Host localhost resolves to non-public address 127.0.0.1')).toBeVisible()
  })

  test('lead capture form submits successfully', async ({ page }) => {
    await page.route('**/report/analyze', async route => {
      await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(FULL_AUDIT) })
    })
    await page.route('**/leads', async route => {
      await route.fulfill({ status: 201, contentType: 'application/json', body: JSON.stringify({ id: 1, email: 'merchant@store.com' }) })
    })

    await page.goto('/')
    await page.getByPlaceholder('https://your-store.com').fill('https://books.toscrape.com')
    await page.getByRole('button', { name: 'Run Agent Audit' }).click()

    await expect(page.locator('input[placeholder="you@company.com"]')).toBeVisible()
    await page.locator('input[placeholder="you@company.com"]').fill('merchant@store.com')
    await page.getByRole('button', { name: 'Kaydet' }).click()

    await expect(page.getByText('Kaydedildi — bu raporu inceleyip size dönüş yapacağız.')).toBeVisible()
  })

  test('admin leads page requires admin token', async ({ page }) => {
    await page.goto('/')
    await page.getByRole('button', { name: 'Leads' }).click()
    await expect(page.getByRole('heading', { name: 'Leads' })).toBeVisible()
    await expect(page.locator('input[placeholder="Admin token"]')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Load leads' })).toBeVisible()
  })

})
