import { test, expect } from '@playwright/test'

// Konsolide tek-sayfa rapor: tek URL → tek sonuç. Jargon yok, müşteri odaklı.

const FULL_AUDIT = {
  url: 'http://localhost:8000',
  total_bytes: 51200,
  script_ratio: 25.4,
  extractable_text_pct: 12.8,
  raw_html: '<html>Mock html</html>',
  markdown: '# Mocked Markdown Output',
  generated_llms_txt:
    '# Mock Store\n\n> Machine-readable storefront summary generated by AGORA.\n\n- [Product A](https://mock/products/a) — Price: 10\n- …preview truncated',
  llms_txt_truncated: true,
  catalog: {
    source: 'products_json',
    total_count: 57,
    visible_to_agent: 3,
    coverage_pct: 5.3,
    sample: [{ name: 'Mock Mousepad XL', url: 'https://mock/products/pad', price: 399 }],
  },
  checklist: {
    llms_txt: { pass_status: true, evidence: 'Mocked llms.txt pass' },
    product_content: { pass_status: true, evidence: 'Mocked product content pass' },
    schema_org: { pass_status: false, evidence: 'Mocked schema.org fail' },
    robots_txt: { pass_status: true, evidence: 'Mocked robots.txt pass' },
  },
}

test.describe('AGORA — konsolide mağaza raporu', () => {

  test('açılışta hero ve tek URL girişi görünür', async ({ page }) => {
    await page.goto('/')
    await expect(page.getByText('AGORA', { exact: true })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Mağazanız yapay zekâya hazır mı?' })).toBeVisible()
    await expect(page.locator('input[placeholder="https://magazaniz.com"]')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Mağazamı Tara' })).toBeVisible()
  })

  test('boş durumda "nasıl çalışır" adımları görünür', async ({ page }) => {
    await page.goto('/')
    await expect(page.getByRole('heading', { name: 'Tarayın' })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Görün' })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Düzeltin' })).toBeVisible()
  })

  test('tarama sonucu tek konsolide raporu gösterir', async ({ page }) => {
    await page.route('**/report/analyze', async route => {
      await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(FULL_AUDIT) })
    })

    await page.goto('/')
    await page.getByPlaceholder('https://magazaniz.com').fill('http://localhost:8000')
    await page.getByRole('button', { name: 'Mağazamı Tara' }).click()

    // 1) Tek sonuç: hazırlık skoru — 3/4 checklist (0.75*60=45) + kapsama 5.3% (0.053*40≈2) = 47
    await expect(page.getByText('Yapay Zekâ Hazırlığı')).toBeVisible()
    await expect(page.getByText('47', { exact: true })).toBeVisible()

    // 2) Ürün görünürlüğü — sade dil
    await expect(page.getByText('Ürünlerinizin kaçını görebiliyorlar?')).toBeVisible()
    await expect(page.getByText('57', { exact: true })).toBeVisible()
    await expect(page.getByText('5.3%')).toBeVisible()

    // 3) Sade kontrol listesi — jargonsuz başlıklar
    await expect(page.getByText('Yapay zekâ için hazır ürün listesi')).toBeVisible()
    await expect(page.getByText('Ürünler yapay zekânın anlayacağı şekilde etiketli')).toBeVisible()

    // 4) Hazırlanan ürün listesi (deliverable) + kilitli önizleme
    await expect(page.getByText('Yapay zekâ için hazırlanmış ürün listesi')).toBeVisible()
    await expect(page.getByText('# Mock Store')).toBeVisible()
    await expect(page.getByText('Bu bir önizleme', { exact: false })).toBeVisible()
    // İndir/kopyala hazır listede yok (yalnızca gizli tam dosya kurulumla gelir)
    await expect(page.getByRole('button', { name: 'Download llms.txt' })).toHaveCount(0)

    // 5) Kilitli canlı ziyaretçiler bölümü
    await expect(page.getByText('Canlı ziyaretçiler')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Kurulumu başlat' })).toBeVisible()

    // 6) E-posta yakalama
    await expect(page.getByRole('heading', { name: 'Tam listeyi ve kurulum adımlarını gönderelim' })).toBeVisible()

    // Gate CTA lead-capture kartına kaydırır
    await page.getByRole('button', { name: 'Tam listeyi isteyin' }).click()
    await expect(page.locator('#lead-capture')).toBeInViewport()

    // "Asistanın gördüğü" görünümü ham çeviriyi gösterir (kopyalanabilir)
    await page.getByRole('button', { name: 'Asistanın gördüğü' }).click()
    await expect(page.getByText('# Mocked Markdown Output')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Kopyala' })).toBeVisible()
  })

  test('teknik detaylar katlanabilir bölümde gizli', async ({ page }) => {
    await page.route('**/report/analyze', async route => {
      await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(FULL_AUDIT) })
    })
    await page.goto('/')
    await page.getByPlaceholder('https://magazaniz.com').fill('http://localhost:8000')
    await page.getByRole('button', { name: 'Mağazamı Tara' }).click()

    const details = page.getByText('Teknik detaylar (isteğe bağlı)')
    await expect(details).toBeVisible()
    // Katlanmışken sayfa boyutu görünmez; açınca görünür
    await details.click()
    await expect(page.getByText('Sayfa boyutu')).toBeVisible()
    await expect(page.getByText('50.0 KB')).toBeVisible()
  })

  test('hata mesajı sade Türkçe gösterilir', async ({ page }) => {
    await page.route('**/report/analyze', async route => {
      await route.fulfill({ status: 400, contentType: 'application/json', body: JSON.stringify({ detail: 'Refused to fetch URL' }) })
    })
    await page.goto('/')
    await page.getByPlaceholder('https://magazaniz.com').fill('http://bad')
    await page.getByRole('button', { name: 'Mağazamı Tara' }).click()
    await expect(page.getByText('Refused to fetch URL')).toBeVisible()
  })

  test('#admin gizli panel yönetim ekranını açar', async ({ page }) => {
    await page.goto('/#admin')
    await expect(page.getByRole('heading', { name: 'Leads' })).toBeVisible()
    await expect(page.locator('input[placeholder="Admin token"]')).toBeVisible()
  })

})
