import { test, expect } from '@playwright/test'

const FULL_AUDIT = {
  url: 'https://books.toscrape.com',
  total_bytes: 51200,
  script_ratio: 25.4,
  extractable_text_pct: 12.8,
  raw_html: '<html><body><h1>Books to Scrape</h1><p>Price: $50.00</p></body></html>',
  markdown: '# Books to Scrape\n\n- [A Light in the Attic](https://books.toscrape.com/a-light) — Price: $51.77',
  generated_llms_txt:
    '# Books to Scrape\n\n> Machine-readable storefront summary generated by AGORA.\n> Source: https://books.toscrape.com\n\n## Products (57)\n\n- [A Light in the Attic](https://books.toscrape.com/a-light) — Price: 51.77\n- …preview truncated: 47+ more product lines in the full file, delivered with the AGORA install package.',
  llms_txt_truncated: true,
  catalog: {
    source: 'products_json',
    total_count: 57,
    visible_to_agent: 3,
    coverage_pct: 5.3,
    sample: [{ name: 'A Light in the Attic', url: 'https://books.toscrape.com/a-light', price: 51.77 }],
  },
  checklist: {
    llms_txt: { pass_status: true, evidence: 'Found /llms.txt with 1 priced product line' },
    product_content: { pass_status: true, evidence: 'Found product indicator tokens: price, product, stock' },
    schema_org: { pass_status: true, evidence: 'Found schema.org Product markup' },
    robots_txt: { pass_status: true, evidence: 'robots.txt does not block known agent user-agents on this path' },
  },
}

test.describe('AGORA — AI Agent Traffic & Storefront Auditor', () => {

  test('initial load: hero, branding, navigation tabs, and audit input are visible', async ({ page }) => {
    await page.goto('/')
    await expect(page.getByText('AGORA', { exact: true })).toBeVisible()
    await expect(page.getByRole('heading', { name: "Your next customer isn't human." })).toBeVisible()
    await expect(page.locator('input[placeholder="https://your-store.com"]')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Run Agent Audit' })).toBeVisible()
  })

  test('landing page renders pipeline steps and agent signatures', async ({ page }) => {
    await page.goto('/')
    await expect(page.getByRole('heading', { name: /See\. Be readable|Gör\. Okunabilir/i })).toBeVisible()
    await expect(page.getByRole('heading', { name: /Detect|Tespit/i })).toBeVisible()
    await expect(page.getByRole('heading', { name: /Audit|Denetle/i })).toBeVisible()
    await expect(page.getByRole('heading', { name: /Serve|Sun/i })).toBeVisible()
    await expect(page.getByText('ChatGPT-User', { exact: true })).toBeVisible()
    await expect(page.getByText('ClaudeBot', { exact: true })).toBeVisible()
  })

  test('tab navigation works smoothly across all views', async ({ page }) => {
    await page.goto('/')

    await page.locator('nav.app-nav').getByRole('button', { name: /Live Request Feed|Canlı İstek Akışı/i }).click()
    await expect(page.getByText(/Hourly Traffic|Saatlik Trafik/i)).toBeVisible()

    await page.locator('nav.app-nav').getByRole('button', { name: /AI Storefront Auditor|AI Mağaza Denetleyici/i }).click()
    await expect(page.getByText(/Ready to audit your storefront|Mağazanızı denetlemeye hazır/i)).toBeVisible()

    await page.locator('nav.app-nav').getByRole('button', { name: /Agent Intelligence|Ajan İstihbaratı/i }).click()
    await expect(page.getByRole('heading', { name: /Agent Demand|Ajan Talebi/i })).toBeVisible()

    await page.locator('nav.app-nav').getByRole('button', { name: /Leads|Kayıtlar/i }).click()
    await expect(page.getByRole('heading', { name: /Leads|Kayıtlar/i })).toBeVisible()

    await page.locator('nav.app-nav').getByRole('button', { name: /Overview|Genel Bakış/i }).click()
    await expect(page.getByText(/Your next customer|Bir sonraki müşteriniz/i)).toBeVisible()
  })

  test('audit execution flow displays results and generated llms.txt', async ({ page }) => {
    await page.route('**/report/analyze', async route => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(FULL_AUDIT),
      })
    })

    await page.goto('/')
    await page.getByPlaceholder('https://your-store.com').fill('https://books.toscrape.com')
    await page.getByRole('button', { name: /Run Agent Audit|Ajan Denetimini Başlat/i }).click()

    await expect(page.getByText(/AI Readiness Checklist|AI Hazırlık Kontrol Listesi/i)).toBeVisible()
    await expect(page.getByText(/Computed Crawl Metrics|Hesaplanan Tarama Metrikleri/i)).toBeVisible()
    await expect(page.getByRole('button', { name: /Generated \/llms\.txt|Üretilen \/llms\.txt/i })).toBeVisible()
    await expect(page.getByText(/Books to Scrape/i).first()).toBeVisible()
  })

  test('quick target buttons populate and trigger audit', async ({ page }) => {
    await page.route('**/report/analyze', async route => {
      await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(FULL_AUDIT) })
    })

    await page.goto('/')
    await page.getByRole('button', { name: /Try the auditor|Denetleyiciyi dene/i }).click()
    await expect(page.getByText(/Ready to audit your storefront|Mağazanızı denetlemeye hazır/i)).toBeVisible()

    await page.getByRole('button', { name: /Books to Scrape/i }).first().click()
    await expect(page.getByText(/Computed Crawl Metrics|Hesaplanan Tarama Metrikleri/i)).toBeVisible()
  })

  test('error message displays when crawl request fails', async ({ page }) => {
    await page.route('**/report/analyze', async route => {
      await route.fulfill({
        status: 400,
        contentType: 'application/json',
        body: JSON.stringify({ detail: 'Refused to fetch URL: Host localhost resolves to non-public address 127.0.0.1' }),
      })
    })

    await page.goto('/')
    await page.getByPlaceholder('https://your-store.com').fill('http://127.0.0.1:8000')
    await page.getByRole('button', { name: /Run Agent Audit|Ajan Denetimini Başlat/i }).click()

    await expect(page.getByText('Refused to fetch URL: Host localhost resolves to non-public address 127.0.0.1')).toBeVisible()
  })

  test('lead capture form submits successfully', async ({ page }) => {
    await page.route('**/report/analyze', async route => {
      await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(FULL_AUDIT) })
    })
    await page.route('**/leads', async route => {
      await route.fulfill({ status: 201, contentType: 'application/json', body: JSON.stringify({ id: 1, email: 'merchant@store.com' }) })
    })

    await page.goto('/')
    await page.getByPlaceholder('https://your-store.com').fill('https://books.toscrape.com')
    await page.getByRole('button', { name: /Run Agent Audit|Ajan Denetimini Başlat/i }).click()

    await expect(page.locator('input[placeholder="you@company.com"]')).toBeVisible()
    await page.locator('input[placeholder="you@company.com"]').fill('merchant@store.com')
    await page.getByRole('button', { name: /Save|Kaydet/i }).click()

    await expect(page.getByText(/Saved|Kaydedildi/i)).toBeVisible()
  })

  test('admin leads page requires admin token', async ({ page }) => {
    await page.goto('/')
    await page.locator('nav.app-nav').getByRole('button', { name: /Leads|Kayıtlar/i }).click()
    await expect(page.getByRole('heading', { name: /Leads|Kayıtlar/i })).toBeVisible()
    await expect(page.locator('input[placeholder="Admin token"]')).toBeVisible()
    await expect(page.getByRole('button', { name: /Load leads|Kayıtları yükle/i })).toBeVisible()
  })

  test('mobile viewport (375x667 iPhone SE) renders responsively with zero horizontal overflow', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 })
    await page.goto('/')

    // Verify hero loads and is visible
    await expect(page.getByRole('heading', { name: /Your next customer|Bir sonraki müşteriniz/i })).toBeVisible()
    await expect(page.getByPlaceholder('https://your-store.com')).toBeVisible()

    // Verify zero horizontal scroll overflow on mobile
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
    expect(overflow).toBe(false)

    // Switch to Auditor on mobile
    await page.locator('nav.app-nav').getByRole('button', { name: /AI Storefront Auditor|AI Mağaza Denetleyici/i }).click()
    await expect(page.getByText(/Ready to audit your storefront|Mağazanızı denetlemeye hazır/i)).toBeVisible()
    const auditorOverflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
    expect(auditorOverflow).toBe(false)

    // Switch to Feed on mobile
    await page.locator('nav.app-nav').getByRole('button', { name: /Live Request Feed|Canlı İstek Akışı/i }).click()
    await expect(page.getByText(/Hourly Traffic|Saatlik Trafik/i)).toBeVisible()
    const feedOverflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
    expect(feedOverflow).toBe(false)
  })

})
